use_frameworks!

platform :ios, '8.0'

target 'ZGReformerKeysKit_Example' do
  pod 'ZGReformerKeysKit', :path => '../'

  target 'ZGReformerKeysKit_Tests' do
    inherit! :search_paths

    
  end
end
